/* This file should be auto-generated by tool, please don't manully modify it.*/
#include "hisi_battery_data_default.c"
#include "hisi_battery_data_feimaotui_1780.c"
#include "hisi_battery_data_feimaotui_1500.c"

static struct hisi_smartstar_coul_battery_data *battery_data_array[] = {
    &default_battery_data,
    &feimaotui_1780_battery_data,
    &feimaotui_1500_battery_data,
};



